### ISSUE TITLE
Board.ResetStyle read only

### ISSUE THREAD

**Issue by aaronmanill** [dotnet/intro-to-dotnet-web-dev#21]
Building a straight copy from the 1-complete folder is throwing the same error in 2 locations:
\1-complete\ConnectFour\Shared\Board.razor(105,4,105,14): error CS0200: Property or indexer 'Board.ResetStyle' cannot be assigned to -- it is read only
\1-complete\ConnectFour\Shared\Board.razor(113,3,113,13): error CS0200: Property or indexer 'Board.ResetStyle' cannot be assigned to -- it is read only

**Comment by aaronmanill** [comment]
there is no set property on ResetStyle, I'm new to C# so had to correct in block format with the following:

`	private string ResetStyle
	{
		get
		{
			return (WinnerMessage == string.Empty) ? "display: none;" : "";
		}
		set { }
	}`

**Comment by strawb2511** [comment]
If you read the README.md and work through the example, the lines
		_if (WinnerMessage != string.Empty) {
			ResetStyle = string.Empty;
		}_
aren't added.
They aren't needed.
@aaronmanill by making the change, you suggested of including a blank _set_ method, you are effectively saying
if the WinnerMessage isn't empty, then do nothing, which makes those lines redundant.

**Comment by jamesmontemagno** [comment]
This was fixed
