### ISSUE TITLE
hello world challenge link leads to 404 error page

### ISSUE THREAD

**Issue by cthecreator** [dotnet/intro-to-dotnet-web-dev#29]
I'm not sure where that link is supposed to lead exactly, but the hello world challenge that I did prior to starting this tutorial was this one [https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/intro](url)

**Comment by katiesavage** [comment]
Thank you for catching that! It should be fixed now.

**Comment by cthecreator** [comment]
Thank you so much, I had another brief issue that should be simple to resolve, but thank you so much for fixing this link, the tutorial was awesome!
